spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  data:
    web:
      pageable:
        one-indexed-parameters:  true
        default-page-size: 5

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true

danolman:
  jwt-key: "1oaAWvrgDcYmUZNqnyhJRQHDfWGkVK3Vnt4J0mn7vy0="
